package dxh.notes.dao;

import dxh.notes.bean.Errornotes;
import dxh.notes.bean.ErrornotesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ErrornotesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table errornotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    long countByExample(ErrornotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table errornotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int deleteByExample(ErrornotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table errornotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table errornotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int insert(Errornotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table errornotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int insertSelective(Errornotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table errornotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    List<Errornotes> selectByExample(ErrornotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table errornotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    Errornotes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table errornotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") Errornotes record, @Param("example") ErrornotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table errornotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByExample(@Param("record") Errornotes record, @Param("example") ErrornotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table errornotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByPrimaryKeySelective(Errornotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table errornotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByPrimaryKey(Errornotes record);
}