package dxh.notes.dao;

import dxh.notes.bean.Like;
import dxh.notes.bean.LikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    long countByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int deleteByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int insert(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int insertSelective(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    List<Like> selectByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    Like selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") Like record, @Param("example") LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByExample(@Param("record") Like record, @Param("example") LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByPrimaryKeySelective(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByPrimaryKey(Like record);
}