package dxh.notes.dao;

import dxh.notes.bean.Studyquestions;
import dxh.notes.bean.StudyquestionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudyquestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyquestions
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    long countByExample(StudyquestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyquestions
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int deleteByExample(StudyquestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyquestions
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyquestions
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int insert(Studyquestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyquestions
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int insertSelective(Studyquestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyquestions
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    List<Studyquestions> selectByExample(StudyquestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyquestions
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    Studyquestions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyquestions
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") Studyquestions record, @Param("example") StudyquestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyquestions
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByExample(@Param("record") Studyquestions record, @Param("example") StudyquestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyquestions
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByPrimaryKeySelective(Studyquestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyquestions
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByPrimaryKey(Studyquestions record);
}