package dxh.notes.dao;

import dxh.notes.bean.Studynotes;
import dxh.notes.bean.StudynotesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudynotesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studynotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    long countByExample(StudynotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studynotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int deleteByExample(StudynotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studynotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studynotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int insert(Studynotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studynotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int insertSelective(Studynotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studynotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    List<Studynotes> selectByExample(StudynotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studynotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    Studynotes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studynotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") Studynotes record, @Param("example") StudynotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studynotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByExample(@Param("record") Studynotes record, @Param("example") StudynotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studynotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByPrimaryKeySelective(Studynotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studynotes
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    int updateByPrimaryKey(Studynotes record);
}