package dxh.notes.bean;

import java.util.Date;

public class Errornotes {
    private Integer id;

    private String cause;

    private String solution;

    private Date createtime;
    private Integer author;

    
    public Errornotes() {
	}

	public Errornotes(String cause, String solution, Date createtime, Integer author) {
		super();
		this.cause = cause;
		this.solution = solution;
		this.createtime = createtime;
		this.author = author;
	}

	@Override
	public String toString() {
		return "Errornotes [id=" + id + ", cause=" + cause + ", solution=" + solution + ", createtime=" + createtime
				+ ", author=" + author + "]";
	}

	public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCause() {
        return cause;
    }

    public void setCause(String cause) {
        this.cause = cause == null ? null : cause.trim();
    }

    public String getSolution() {
        return solution;
    }

    public void setSolution(String solution) {
        this.solution = solution == null ? null : solution.trim();
    }
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column errornotes.createtime
     *
     * @param createtime the value for errornotes.createtime
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column errornotes.author
     *
     * @return the value of errornotes.author
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public Integer getAuthor() {
        return author;
    }

    public void setAuthor(Integer author) {
        this.author = author;
    }
}