package dxh.notes.bean;

public class Like {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.id
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.author
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private Integer author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.target
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private Integer target;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.id
     *
     * @return the value of like.id
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.id
     *
     * @param id the value for like.id
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.author
     *
     * @return the value of like.author
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.author
     *
     * @param author the value for like.author
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setAuthor(Integer author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.target
     *
     * @return the value of like.target
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public Integer getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.target
     *
     * @param target the value for like.target
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setTarget(Integer target) {
        this.target = target;
    }
}