package dxh.notes.bean;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.id
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.username
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.password
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.nickname
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.realname
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.gender
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.age
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.contact
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private Integer contact;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.id
     *
     * @return the value of manager.id
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.id
     *
     * @param id the value for manager.id
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.username
     *
     * @return the value of manager.username
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.username
     *
     * @param username the value for manager.username
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.password
     *
     * @return the value of manager.password
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.password
     *
     * @param password the value for manager.password
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.nickname
     *
     * @return the value of manager.nickname
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.nickname
     *
     * @param nickname the value for manager.nickname
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.realname
     *
     * @return the value of manager.realname
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.realname
     *
     * @param realname the value for manager.realname
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.gender
     *
     * @return the value of manager.gender
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.gender
     *
     * @param gender the value for manager.gender
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.age
     *
     * @return the value of manager.age
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.age
     *
     * @param age the value for manager.age
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.contact
     *
     * @return the value of manager.contact
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public Integer getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.contact
     *
     * @param contact the value for manager.contact
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setContact(Integer contact) {
        this.contact = contact;
    }

	@Override
	public String toString() {
		return "Manager [id=" + id + ", username=" + username + ", password=" + password + ", nickname=" + nickname
				+ ", realname=" + realname + ", gender=" + gender + ", age=" + age + ", contact=" + contact + "]";
	}
    
    
}