package dxh.notes.bean;

import java.util.Date;

public class Studyplans {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyplans.id
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyplans.content
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyplans.createtime
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyplans.author
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    private Integer author;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyplans.id
     *
     * @return the value of studyplans.id
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyplans.id
     *
     * @param id the value for studyplans.id
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyplans.content
     *
     * @return the value of studyplans.content
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyplans.content
     *
     * @param content the value for studyplans.content
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyplans.createtime
     *
     * @return the value of studyplans.createtime
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyplans.createtime
     *
     * @param createtime the value for studyplans.createtime
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyplans.author
     *
     * @return the value of studyplans.author
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyplans.author
     *
     * @param author the value for studyplans.author
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setAuthor(Integer author) {
        this.author = author;
    }
}