package dxh.notes.bean;

import java.util.Date;

public class Studynotes {
    
    private Integer id;
   
    private String title;
    
    private String content;
    
    private Date createtime;

    private Integer author;
   
    public Studynotes() {
	
    }

	public Studynotes(String title, String content, Date createtime, Integer author) {
		super();
		this.title = title;
		this.content = content;
		this.createtime = createtime;
		this.author = author;
	}



	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studynotes.id
     *
     * @param id the value for studynotes.id
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studynotes.title
     *
     * @return the value of studynotes.title
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studynotes.title
     *
     * @param title the value for studynotes.title
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studynotes.content
     *
     * @return the value of studynotes.content
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studynotes.content
     *
     * @param content the value for studynotes.content
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studynotes.createtime
     *
     * @return the value of studynotes.createtime
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studynotes.createtime
     *
     * @param createtime the value for studynotes.createtime
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studynotes.author
     *
     * @return the value of studynotes.author
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studynotes.author
     *
     * @param author the value for studynotes.author
     *
     * @mbg.generated Mon Oct 22 11:16:56 CST 2018
     */
    public void setAuthor(Integer author) {
        this.author = author;
    }

	@Override
	public String toString() {
		return "Studynotes [id=" + id + ", title=" + title + ", content=" + content + ", createtime=" + createtime
				+ ", author=" + author + "]";
	}
    
}